title = "Writing an OS in Rust"
base_url = "https://os.phil-opp.com"
description = "This blog series creates a small operating system in the Rust programming language. Each post is a small tutorial and includes all needed code."

highlight_code = true
highlight_theme = "visual-studio-dark"
generate_feed = true
feed_filename = "rss.xml"

languages = [
    { code = "zh-CN" }, # Chinese (simplified)
    { code = "zh-TW" }, # Chinese (traditional)
    { code = "ja" }, # Japanese
    { code = "fa" }, # Persian
]

ignored_content = ["*/README.md"]

[link_checker]
skip_prefixes = [
    "https://crates.io/crates", # see https://github.com/rust-lang/crates.io/issues/788
    "https://www.amd.com/system/files/TechDocs/", # seems to have problems with PDFs
    "https://developer.apple.com/library/archive/qa/qa1118/_index.html", # results in a 401 (I don't know why)
    "https://github.com", # rate limiting often leads to "Error 429 Too Many Requests"
    "https://www.linkedin.com/", # seems to send invalid HTTP status codes
]
skip_anchor_prefixes = [
     "https://github.com/", # see https://github.com/getzola/zola/issues/805
     "https://docs.rs/x86_64/0.1.2/src/", # source code highlight
]

[extra]
subtitle = "Philipp Oppermann's blog"
author = { name = "Philipp Oppermann" }

[translations.en]
lang_name = "English"
toc = "Table Of Contents"
all_posts = "« All Posts"
comments = "Comments"
comments_notice = "Please leave your comments in English if possible."
readmore = "read&nbsp;more&nbsp;»"
not_translated = "(This post is not translated yet.)"
translated_content = "Translated Content:"
translated_content_notice = "This is a community translation of the <strong><a href=\"{{ original.permalink }}\">{{ original.title }}</a></strong> post. It might be incomplete, outdated or contain errors. Please report any issues!"
translated_by = "Translation By"
word_seprator = "and"

[translations.zh-CN]
lang_name = "Chinese (simplified)"
toc = "Table Of Contents"
all_posts = "« All Posts"
comments = "Comments"
comments_notice = "Please leave your comments in English if possible."
readmore = "read&nbsp;more&nbsp;»"
not_translated = "(This post is not translated yet.)"
translated_content = "Translated Content:"
translated_content_notice = "This is a community translation of the <strong><a href=\"{{ original.permalink }}\">{{ original.title }}</a></strong> post. It might be incomplete, outdated or contain errors. Please report any issues!"
translated_by = "Translation By"
word_seprator = "and"

[translations.zh-TW]
lang_name = "Chinese (traditional)"
toc = "Table Of Contents"
all_posts = "« All Posts"
comments = "Comments"
comments_notice = "Please leave your comments in English if possible."
readmore = "read&nbsp;more&nbsp;»"
not_translated = "(This post is not translated yet.)"
translated_content = "Translated Content:"
translated_content_notice = "This is a community translation of the <strong><a href=\"{{ original.permalink }}\">{{ original.title }}</a></strong> post. It might be incomplete, outdated or contain errors. Please report any issues!"
translated_by = "Translation By"
word_seprator = "and"

[translations.ja]
lang_name = "Japanese"
toc = "Table Of Contents"
all_posts = "« All Posts"
comments = "Comments"
comments_notice = "Please leave your comments in English if possible."
readmore = "read&nbsp;more&nbsp;»"
not_translated = "(This post is not translated yet.)"
translated_content = "Translated Content:"
translated_content_notice = "This is a community translation of the <strong><a href=\"{{ original.permalink }}\">{{ original.title }}</a></strong> post. It might be incomplete, outdated or contain errors. Please report any issues!"
translated_by = "Translation By"
word_seprator = "and"

[translations.fa]
lang_name = "Persian"
toc = "فهرست مطالب"
all_posts = "« همه پست‌ها"
comments = "نظرات"
comments_notice = "لطفا نظرات خود را در صورت امکان به انگلیسی بنویسید."
readmore = "ادامه‌مطلب»"
not_translated = "(این پست هنوز ترجمه نشده است.)"
translated_content = "محتوای ترجمه شده:"
translated_content_notice = "این یک ترجمه از جامعه کاربران برای پست <strong><a href=\"_original.permalink_\">_original.title_</a></strong> است. ممکن است ناقص ، منسوخ شده یا دارای خطا باشد. لطفا هر گونه مشکل را گزارش دهید!"
translated_by = "ترجمه توسط"
word_seprator = "و"
